// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_request.proto

package wg_test.chat.proto;

public final class MessageRequest {
  private MessageRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SendMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wg_test.SendMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 toId = 1;</code>
     */
    int getToId();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code wg_test.SendMessage}
   */
  public  static final class SendMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wg_test.SendMessage)
      SendMessageOrBuilder {
    // Use SendMessage.newBuilder() to construct.
    private SendMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendMessage() {
      toId_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SendMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              toId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wg_test.chat.proto.MessageRequest.internal_static_wg_test_SendMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wg_test.chat.proto.MessageRequest.internal_static_wg_test_SendMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wg_test.chat.proto.MessageRequest.SendMessage.class, wg_test.chat.proto.MessageRequest.SendMessage.Builder.class);
    }

    public static final int TOID_FIELD_NUMBER = 1;
    private int toId_;
    /**
     * <code>int32 toId = 1;</code>
     */
    public int getToId() {
      return toId_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (toId_ != 0) {
        output.writeInt32(1, toId_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (toId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, toId_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wg_test.chat.proto.MessageRequest.SendMessage)) {
        return super.equals(obj);
      }
      wg_test.chat.proto.MessageRequest.SendMessage other = (wg_test.chat.proto.MessageRequest.SendMessage) obj;

      boolean result = true;
      result = result && (getToId()
          == other.getToId());
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOID_FIELD_NUMBER;
      hash = (53 * hash) + getToId();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.SendMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wg_test.chat.proto.MessageRequest.SendMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wg_test.SendMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wg_test.SendMessage)
        wg_test.chat.proto.MessageRequest.SendMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_SendMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_SendMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wg_test.chat.proto.MessageRequest.SendMessage.class, wg_test.chat.proto.MessageRequest.SendMessage.Builder.class);
      }

      // Construct using wg_test.chat.proto.MessageRequest.SendMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        toId_ = 0;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_SendMessage_descriptor;
      }

      public wg_test.chat.proto.MessageRequest.SendMessage getDefaultInstanceForType() {
        return wg_test.chat.proto.MessageRequest.SendMessage.getDefaultInstance();
      }

      public wg_test.chat.proto.MessageRequest.SendMessage build() {
        wg_test.chat.proto.MessageRequest.SendMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wg_test.chat.proto.MessageRequest.SendMessage buildPartial() {
        wg_test.chat.proto.MessageRequest.SendMessage result = new wg_test.chat.proto.MessageRequest.SendMessage(this);
        result.toId_ = toId_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wg_test.chat.proto.MessageRequest.SendMessage) {
          return mergeFrom((wg_test.chat.proto.MessageRequest.SendMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wg_test.chat.proto.MessageRequest.SendMessage other) {
        if (other == wg_test.chat.proto.MessageRequest.SendMessage.getDefaultInstance()) return this;
        if (other.getToId() != 0) {
          setToId(other.getToId());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wg_test.chat.proto.MessageRequest.SendMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wg_test.chat.proto.MessageRequest.SendMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int toId_ ;
      /**
       * <code>int32 toId = 1;</code>
       */
      public int getToId() {
        return toId_;
      }
      /**
       * <code>int32 toId = 1;</code>
       */
      public Builder setToId(int value) {
        
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 toId = 1;</code>
       */
      public Builder clearToId() {
        
        toId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:wg_test.SendMessage)
    }

    // @@protoc_insertion_point(class_scope:wg_test.SendMessage)
    private static final wg_test.chat.proto.MessageRequest.SendMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wg_test.chat.proto.MessageRequest.SendMessage();
    }

    public static wg_test.chat.proto.MessageRequest.SendMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendMessage>
        PARSER = new com.google.protobuf.AbstractParser<SendMessage>() {
      public SendMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SendMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendMessage> getParserForType() {
      return PARSER;
    }

    public wg_test.chat.proto.MessageRequest.SendMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wg_test.UpdateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageId = 1;</code>
     */
    int getMessageId();

    /**
     * <code>int32 chatId = 2;</code>
     */
    int getChatId();

    /**
     * <code>string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code wg_test.UpdateMessage}
   */
  public  static final class UpdateMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wg_test.UpdateMessage)
      UpdateMessageOrBuilder {
    // Use UpdateMessage.newBuilder() to construct.
    private UpdateMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateMessage() {
      messageId_ = 0;
      chatId_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 16: {

              chatId_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wg_test.chat.proto.MessageRequest.internal_static_wg_test_UpdateMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wg_test.chat.proto.MessageRequest.internal_static_wg_test_UpdateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wg_test.chat.proto.MessageRequest.UpdateMessage.class, wg_test.chat.proto.MessageRequest.UpdateMessage.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>int32 messageId = 1;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int CHATID_FIELD_NUMBER = 2;
    private int chatId_;
    /**
     * <code>int32 chatId = 2;</code>
     */
    public int getChatId() {
      return chatId_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (chatId_ != 0) {
        output.writeInt32(2, chatId_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (chatId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chatId_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wg_test.chat.proto.MessageRequest.UpdateMessage)) {
        return super.equals(obj);
      }
      wg_test.chat.proto.MessageRequest.UpdateMessage other = (wg_test.chat.proto.MessageRequest.UpdateMessage) obj;

      boolean result = true;
      result = result && (getMessageId()
          == other.getMessageId());
      result = result && (getChatId()
          == other.getChatId());
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + CHATID_FIELD_NUMBER;
      hash = (53 * hash) + getChatId();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.UpdateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wg_test.chat.proto.MessageRequest.UpdateMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wg_test.UpdateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wg_test.UpdateMessage)
        wg_test.chat.proto.MessageRequest.UpdateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_UpdateMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_UpdateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wg_test.chat.proto.MessageRequest.UpdateMessage.class, wg_test.chat.proto.MessageRequest.UpdateMessage.Builder.class);
      }

      // Construct using wg_test.chat.proto.MessageRequest.UpdateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        chatId_ = 0;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_UpdateMessage_descriptor;
      }

      public wg_test.chat.proto.MessageRequest.UpdateMessage getDefaultInstanceForType() {
        return wg_test.chat.proto.MessageRequest.UpdateMessage.getDefaultInstance();
      }

      public wg_test.chat.proto.MessageRequest.UpdateMessage build() {
        wg_test.chat.proto.MessageRequest.UpdateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wg_test.chat.proto.MessageRequest.UpdateMessage buildPartial() {
        wg_test.chat.proto.MessageRequest.UpdateMessage result = new wg_test.chat.proto.MessageRequest.UpdateMessage(this);
        result.messageId_ = messageId_;
        result.chatId_ = chatId_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wg_test.chat.proto.MessageRequest.UpdateMessage) {
          return mergeFrom((wg_test.chat.proto.MessageRequest.UpdateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wg_test.chat.proto.MessageRequest.UpdateMessage other) {
        if (other == wg_test.chat.proto.MessageRequest.UpdateMessage.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (other.getChatId() != 0) {
          setChatId(other.getChatId());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wg_test.chat.proto.MessageRequest.UpdateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wg_test.chat.proto.MessageRequest.UpdateMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <code>int32 messageId = 1;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>int32 messageId = 1;</code>
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private int chatId_ ;
      /**
       * <code>int32 chatId = 2;</code>
       */
      public int getChatId() {
        return chatId_;
      }
      /**
       * <code>int32 chatId = 2;</code>
       */
      public Builder setChatId(int value) {
        
        chatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chatId = 2;</code>
       */
      public Builder clearChatId() {
        
        chatId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:wg_test.UpdateMessage)
    }

    // @@protoc_insertion_point(class_scope:wg_test.UpdateMessage)
    private static final wg_test.chat.proto.MessageRequest.UpdateMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wg_test.chat.proto.MessageRequest.UpdateMessage();
    }

    public static wg_test.chat.proto.MessageRequest.UpdateMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateMessage>
        PARSER = new com.google.protobuf.AbstractParser<UpdateMessage>() {
      public UpdateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateMessage> getParserForType() {
      return PARSER;
    }

    public wg_test.chat.proto.MessageRequest.UpdateMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeleteMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wg_test.DeleteMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 messageId = 1;</code>
     */
    int getMessageId();

    /**
     * <code>int32 chatId = 2;</code>
     */
    int getChatId();
  }
  /**
   * Protobuf type {@code wg_test.DeleteMessage}
   */
  public  static final class DeleteMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wg_test.DeleteMessage)
      DeleteMessageOrBuilder {
    // Use DeleteMessage.newBuilder() to construct.
    private DeleteMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeleteMessage() {
      messageId_ = 0;
      chatId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DeleteMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              messageId_ = input.readInt32();
              break;
            }
            case 16: {

              chatId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wg_test.chat.proto.MessageRequest.internal_static_wg_test_DeleteMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wg_test.chat.proto.MessageRequest.internal_static_wg_test_DeleteMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wg_test.chat.proto.MessageRequest.DeleteMessage.class, wg_test.chat.proto.MessageRequest.DeleteMessage.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageId_;
    /**
     * <code>int32 messageId = 1;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int CHATID_FIELD_NUMBER = 2;
    private int chatId_;
    /**
     * <code>int32 chatId = 2;</code>
     */
    public int getChatId() {
      return chatId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0) {
        output.writeInt32(1, messageId_);
      }
      if (chatId_ != 0) {
        output.writeInt32(2, chatId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageId_);
      }
      if (chatId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, chatId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wg_test.chat.proto.MessageRequest.DeleteMessage)) {
        return super.equals(obj);
      }
      wg_test.chat.proto.MessageRequest.DeleteMessage other = (wg_test.chat.proto.MessageRequest.DeleteMessage) obj;

      boolean result = true;
      result = result && (getMessageId()
          == other.getMessageId());
      result = result && (getChatId()
          == other.getChatId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId();
      hash = (37 * hash) + CHATID_FIELD_NUMBER;
      hash = (53 * hash) + getChatId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.DeleteMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wg_test.chat.proto.MessageRequest.DeleteMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wg_test.DeleteMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wg_test.DeleteMessage)
        wg_test.chat.proto.MessageRequest.DeleteMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_DeleteMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_DeleteMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wg_test.chat.proto.MessageRequest.DeleteMessage.class, wg_test.chat.proto.MessageRequest.DeleteMessage.Builder.class);
      }

      // Construct using wg_test.chat.proto.MessageRequest.DeleteMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = 0;

        chatId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_DeleteMessage_descriptor;
      }

      public wg_test.chat.proto.MessageRequest.DeleteMessage getDefaultInstanceForType() {
        return wg_test.chat.proto.MessageRequest.DeleteMessage.getDefaultInstance();
      }

      public wg_test.chat.proto.MessageRequest.DeleteMessage build() {
        wg_test.chat.proto.MessageRequest.DeleteMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wg_test.chat.proto.MessageRequest.DeleteMessage buildPartial() {
        wg_test.chat.proto.MessageRequest.DeleteMessage result = new wg_test.chat.proto.MessageRequest.DeleteMessage(this);
        result.messageId_ = messageId_;
        result.chatId_ = chatId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wg_test.chat.proto.MessageRequest.DeleteMessage) {
          return mergeFrom((wg_test.chat.proto.MessageRequest.DeleteMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wg_test.chat.proto.MessageRequest.DeleteMessage other) {
        if (other == wg_test.chat.proto.MessageRequest.DeleteMessage.getDefaultInstance()) return this;
        if (other.getMessageId() != 0) {
          setMessageId(other.getMessageId());
        }
        if (other.getChatId() != 0) {
          setChatId(other.getChatId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wg_test.chat.proto.MessageRequest.DeleteMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wg_test.chat.proto.MessageRequest.DeleteMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageId_ ;
      /**
       * <code>int32 messageId = 1;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>int32 messageId = 1;</code>
       */
      public Builder setMessageId(int value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0;
        onChanged();
        return this;
      }

      private int chatId_ ;
      /**
       * <code>int32 chatId = 2;</code>
       */
      public int getChatId() {
        return chatId_;
      }
      /**
       * <code>int32 chatId = 2;</code>
       */
      public Builder setChatId(int value) {
        
        chatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chatId = 2;</code>
       */
      public Builder clearChatId() {
        
        chatId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:wg_test.DeleteMessage)
    }

    // @@protoc_insertion_point(class_scope:wg_test.DeleteMessage)
    private static final wg_test.chat.proto.MessageRequest.DeleteMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wg_test.chat.proto.MessageRequest.DeleteMessage();
    }

    public static wg_test.chat.proto.MessageRequest.DeleteMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeleteMessage>
        PARSER = new com.google.protobuf.AbstractParser<DeleteMessage>() {
      public DeleteMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DeleteMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeleteMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeleteMessage> getParserForType() {
      return PARSER;
    }

    public wg_test.chat.proto.MessageRequest.DeleteMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wg_test.ListMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 chatId = 1;</code>
     */
    int getChatId();

    /**
     * <code>int64 horizon = 2;</code>
     */
    long getHorizon();
  }
  /**
   * Protobuf type {@code wg_test.ListMessage}
   */
  public  static final class ListMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wg_test.ListMessage)
      ListMessageOrBuilder {
    // Use ListMessage.newBuilder() to construct.
    private ListMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListMessage() {
      chatId_ = 0;
      horizon_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ListMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              chatId_ = input.readInt32();
              break;
            }
            case 16: {

              horizon_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wg_test.chat.proto.MessageRequest.internal_static_wg_test_ListMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wg_test.chat.proto.MessageRequest.internal_static_wg_test_ListMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wg_test.chat.proto.MessageRequest.ListMessage.class, wg_test.chat.proto.MessageRequest.ListMessage.Builder.class);
    }

    public static final int CHATID_FIELD_NUMBER = 1;
    private int chatId_;
    /**
     * <code>int32 chatId = 1;</code>
     */
    public int getChatId() {
      return chatId_;
    }

    public static final int HORIZON_FIELD_NUMBER = 2;
    private long horizon_;
    /**
     * <code>int64 horizon = 2;</code>
     */
    public long getHorizon() {
      return horizon_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chatId_ != 0) {
        output.writeInt32(1, chatId_);
      }
      if (horizon_ != 0L) {
        output.writeInt64(2, horizon_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chatId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chatId_);
      }
      if (horizon_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, horizon_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wg_test.chat.proto.MessageRequest.ListMessage)) {
        return super.equals(obj);
      }
      wg_test.chat.proto.MessageRequest.ListMessage other = (wg_test.chat.proto.MessageRequest.ListMessage) obj;

      boolean result = true;
      result = result && (getChatId()
          == other.getChatId());
      result = result && (getHorizon()
          == other.getHorizon());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHATID_FIELD_NUMBER;
      hash = (53 * hash) + getChatId();
      hash = (37 * hash) + HORIZON_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHorizon());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.MessageRequest.ListMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wg_test.chat.proto.MessageRequest.ListMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wg_test.ListMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wg_test.ListMessage)
        wg_test.chat.proto.MessageRequest.ListMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_ListMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_ListMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wg_test.chat.proto.MessageRequest.ListMessage.class, wg_test.chat.proto.MessageRequest.ListMessage.Builder.class);
      }

      // Construct using wg_test.chat.proto.MessageRequest.ListMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        chatId_ = 0;

        horizon_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wg_test.chat.proto.MessageRequest.internal_static_wg_test_ListMessage_descriptor;
      }

      public wg_test.chat.proto.MessageRequest.ListMessage getDefaultInstanceForType() {
        return wg_test.chat.proto.MessageRequest.ListMessage.getDefaultInstance();
      }

      public wg_test.chat.proto.MessageRequest.ListMessage build() {
        wg_test.chat.proto.MessageRequest.ListMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wg_test.chat.proto.MessageRequest.ListMessage buildPartial() {
        wg_test.chat.proto.MessageRequest.ListMessage result = new wg_test.chat.proto.MessageRequest.ListMessage(this);
        result.chatId_ = chatId_;
        result.horizon_ = horizon_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wg_test.chat.proto.MessageRequest.ListMessage) {
          return mergeFrom((wg_test.chat.proto.MessageRequest.ListMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wg_test.chat.proto.MessageRequest.ListMessage other) {
        if (other == wg_test.chat.proto.MessageRequest.ListMessage.getDefaultInstance()) return this;
        if (other.getChatId() != 0) {
          setChatId(other.getChatId());
        }
        if (other.getHorizon() != 0L) {
          setHorizon(other.getHorizon());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wg_test.chat.proto.MessageRequest.ListMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wg_test.chat.proto.MessageRequest.ListMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int chatId_ ;
      /**
       * <code>int32 chatId = 1;</code>
       */
      public int getChatId() {
        return chatId_;
      }
      /**
       * <code>int32 chatId = 1;</code>
       */
      public Builder setChatId(int value) {
        
        chatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chatId = 1;</code>
       */
      public Builder clearChatId() {
        
        chatId_ = 0;
        onChanged();
        return this;
      }

      private long horizon_ ;
      /**
       * <code>int64 horizon = 2;</code>
       */
      public long getHorizon() {
        return horizon_;
      }
      /**
       * <code>int64 horizon = 2;</code>
       */
      public Builder setHorizon(long value) {
        
        horizon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 horizon = 2;</code>
       */
      public Builder clearHorizon() {
        
        horizon_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:wg_test.ListMessage)
    }

    // @@protoc_insertion_point(class_scope:wg_test.ListMessage)
    private static final wg_test.chat.proto.MessageRequest.ListMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wg_test.chat.proto.MessageRequest.ListMessage();
    }

    public static wg_test.chat.proto.MessageRequest.ListMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListMessage>
        PARSER = new com.google.protobuf.AbstractParser<ListMessage>() {
      public ListMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ListMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListMessage> getParserForType() {
      return PARSER;
    }

    public wg_test.chat.proto.MessageRequest.ListMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wg_test_SendMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wg_test_SendMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wg_test_UpdateMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wg_test_UpdateMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wg_test_DeleteMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wg_test_DeleteMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wg_test_ListMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wg_test_ListMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025message_request.proto\022\007wg_test\",\n\013Send" +
      "Message\022\014\n\004toId\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"C" +
      "\n\rUpdateMessage\022\021\n\tmessageId\030\001 \001(\005\022\016\n\006ch" +
      "atId\030\002 \001(\005\022\017\n\007message\030\003 \001(\t\"2\n\rDeleteMes" +
      "sage\022\021\n\tmessageId\030\001 \001(\005\022\016\n\006chatId\030\002 \001(\005\"" +
      ".\n\013ListMessage\022\016\n\006chatId\030\001 \001(\005\022\017\n\007horizo" +
      "n\030\002 \001(\003B\024\n\022wg_test.chat.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wg_test_SendMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wg_test_SendMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wg_test_SendMessage_descriptor,
        new java.lang.String[] { "ToId", "Message", });
    internal_static_wg_test_UpdateMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wg_test_UpdateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wg_test_UpdateMessage_descriptor,
        new java.lang.String[] { "MessageId", "ChatId", "Message", });
    internal_static_wg_test_DeleteMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wg_test_DeleteMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wg_test_DeleteMessage_descriptor,
        new java.lang.String[] { "MessageId", "ChatId", });
    internal_static_wg_test_ListMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_wg_test_ListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wg_test_ListMessage_descriptor,
        new java.lang.String[] { "ChatId", "Horizon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
