// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package wg_test.chat.proto;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wg_test.ServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
     */
    wg_test.chat.proto.Response.ServerMessage.MessageType getType();

    /**
     * <code>bool success = 2;</code>
     */
    boolean getSuccess();

    /**
     * <code>bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code wg_test.ServerMessage}
   */
  public  static final class ServerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wg_test.ServerMessage)
      ServerMessageOrBuilder {
    // Use ServerMessage.newBuilder() to construct.
    private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerMessage() {
      type_ = 0;
      success_ = false;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              success_ = input.readBool();
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wg_test.chat.proto.Response.internal_static_wg_test_ServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wg_test.chat.proto.Response.internal_static_wg_test_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wg_test.chat.proto.Response.ServerMessage.class, wg_test.chat.proto.Response.ServerMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code wg_test.ServerMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AUTH = 0;</code>
       */
      AUTH(0),
      /**
       * <code>REGISTER = 1;</code>
       */
      REGISTER(1),
      /**
       * <code>CHECK_USER_NAME = 2;</code>
       */
      CHECK_USER_NAME(2),
      /**
       * <code>VALIDATE_TOKEN = 3;</code>
       */
      VALIDATE_TOKEN(3),
      /**
       * <code>REGENERATE_TOKEN = 4;</code>
       */
      REGENERATE_TOKEN(4),
      /**
       * <code>USER_LIST = 10;</code>
       */
      USER_LIST(10),
      /**
       * <code>USER_STATUS_CHANGE = 11;</code>
       */
      USER_STATUS_CHANGE(11),
      /**
       * <code>NEW_USER = 12;</code>
       */
      NEW_USER(12),
      /**
       * <code>SEND_MESSAGE = 20;</code>
       */
      SEND_MESSAGE(20),
      /**
       * <code>UPDATE_MESSAGE = 21;</code>
       */
      UPDATE_MESSAGE(21),
      /**
       * <code>DELETE_MESSAGE = 22;</code>
       */
      DELETE_MESSAGE(22),
      /**
       * <code>LIST_MESSAGES = 23;</code>
       */
      LIST_MESSAGES(23),
      /**
       * <code>NEW_MESSAGE = 24;</code>
       */
      NEW_MESSAGE(24),
      /**
       * <code>UPDATED_MESSAGE = 25;</code>
       */
      UPDATED_MESSAGE(25),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>AUTH = 0;</code>
       */
      public static final int AUTH_VALUE = 0;
      /**
       * <code>REGISTER = 1;</code>
       */
      public static final int REGISTER_VALUE = 1;
      /**
       * <code>CHECK_USER_NAME = 2;</code>
       */
      public static final int CHECK_USER_NAME_VALUE = 2;
      /**
       * <code>VALIDATE_TOKEN = 3;</code>
       */
      public static final int VALIDATE_TOKEN_VALUE = 3;
      /**
       * <code>REGENERATE_TOKEN = 4;</code>
       */
      public static final int REGENERATE_TOKEN_VALUE = 4;
      /**
       * <code>USER_LIST = 10;</code>
       */
      public static final int USER_LIST_VALUE = 10;
      /**
       * <code>USER_STATUS_CHANGE = 11;</code>
       */
      public static final int USER_STATUS_CHANGE_VALUE = 11;
      /**
       * <code>NEW_USER = 12;</code>
       */
      public static final int NEW_USER_VALUE = 12;
      /**
       * <code>SEND_MESSAGE = 20;</code>
       */
      public static final int SEND_MESSAGE_VALUE = 20;
      /**
       * <code>UPDATE_MESSAGE = 21;</code>
       */
      public static final int UPDATE_MESSAGE_VALUE = 21;
      /**
       * <code>DELETE_MESSAGE = 22;</code>
       */
      public static final int DELETE_MESSAGE_VALUE = 22;
      /**
       * <code>LIST_MESSAGES = 23;</code>
       */
      public static final int LIST_MESSAGES_VALUE = 23;
      /**
       * <code>NEW_MESSAGE = 24;</code>
       */
      public static final int NEW_MESSAGE_VALUE = 24;
      /**
       * <code>UPDATED_MESSAGE = 25;</code>
       */
      public static final int UPDATED_MESSAGE_VALUE = 25;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return AUTH;
          case 1: return REGISTER;
          case 2: return CHECK_USER_NAME;
          case 3: return VALIDATE_TOKEN;
          case 4: return REGENERATE_TOKEN;
          case 10: return USER_LIST;
          case 11: return USER_STATUS_CHANGE;
          case 12: return NEW_USER;
          case 20: return SEND_MESSAGE;
          case 21: return UPDATE_MESSAGE;
          case 22: return DELETE_MESSAGE;
          case 23: return LIST_MESSAGES;
          case 24: return NEW_MESSAGE;
          case 25: return UPDATED_MESSAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return wg_test.chat.proto.Response.ServerMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:wg_test.ServerMessage.MessageType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
     */
    public wg_test.chat.proto.Response.ServerMessage.MessageType getType() {
      wg_test.chat.proto.Response.ServerMessage.MessageType result = wg_test.chat.proto.Response.ServerMessage.MessageType.valueOf(type_);
      return result == null ? wg_test.chat.proto.Response.ServerMessage.MessageType.UNRECOGNIZED : result;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>bool success = 2;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != wg_test.chat.proto.Response.ServerMessage.MessageType.AUTH.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != wg_test.chat.proto.Response.ServerMessage.MessageType.AUTH.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wg_test.chat.proto.Response.ServerMessage)) {
        return super.equals(obj);
      }
      wg_test.chat.proto.Response.ServerMessage other = (wg_test.chat.proto.Response.ServerMessage) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wg_test.chat.proto.Response.ServerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wg_test.chat.proto.Response.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wg_test.chat.proto.Response.ServerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wg_test.ServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wg_test.ServerMessage)
        wg_test.chat.proto.Response.ServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wg_test.chat.proto.Response.internal_static_wg_test_ServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wg_test.chat.proto.Response.internal_static_wg_test_ServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wg_test.chat.proto.Response.ServerMessage.class, wg_test.chat.proto.Response.ServerMessage.Builder.class);
      }

      // Construct using wg_test.chat.proto.Response.ServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        success_ = false;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wg_test.chat.proto.Response.internal_static_wg_test_ServerMessage_descriptor;
      }

      public wg_test.chat.proto.Response.ServerMessage getDefaultInstanceForType() {
        return wg_test.chat.proto.Response.ServerMessage.getDefaultInstance();
      }

      public wg_test.chat.proto.Response.ServerMessage build() {
        wg_test.chat.proto.Response.ServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public wg_test.chat.proto.Response.ServerMessage buildPartial() {
        wg_test.chat.proto.Response.ServerMessage result = new wg_test.chat.proto.Response.ServerMessage(this);
        result.type_ = type_;
        result.success_ = success_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wg_test.chat.proto.Response.ServerMessage) {
          return mergeFrom((wg_test.chat.proto.Response.ServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wg_test.chat.proto.Response.ServerMessage other) {
        if (other == wg_test.chat.proto.Response.ServerMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wg_test.chat.proto.Response.ServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wg_test.chat.proto.Response.ServerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
       */
      public wg_test.chat.proto.Response.ServerMessage.MessageType getType() {
        wg_test.chat.proto.Response.ServerMessage.MessageType result = wg_test.chat.proto.Response.ServerMessage.MessageType.valueOf(type_);
        return result == null ? wg_test.chat.proto.Response.ServerMessage.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
       */
      public Builder setType(wg_test.chat.proto.Response.ServerMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.wg_test.ServerMessage.MessageType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 2;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 2;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:wg_test.ServerMessage)
    }

    // @@protoc_insertion_point(class_scope:wg_test.ServerMessage)
    private static final wg_test.chat.proto.Response.ServerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wg_test.chat.proto.Response.ServerMessage();
    }

    public static wg_test.chat.proto.Response.ServerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
      public ServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMessage> getParserForType() {
      return PARSER;
    }

    public wg_test.chat.proto.Response.ServerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wg_test_ServerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wg_test_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\022\007wg_test\"\357\002\n\rServerMess" +
      "age\0220\n\004type\030\001 \001(\0162\".wg_test.ServerMessag" +
      "e.MessageType\022\017\n\007success\030\002 \001(\010\022\014\n\004data\030\003" +
      " \001(\014\"\214\002\n\013MessageType\022\010\n\004AUTH\020\000\022\014\n\010REGIST" +
      "ER\020\001\022\023\n\017CHECK_USER_NAME\020\002\022\022\n\016VALIDATE_TO" +
      "KEN\020\003\022\024\n\020REGENERATE_TOKEN\020\004\022\r\n\tUSER_LIST" +
      "\020\n\022\026\n\022USER_STATUS_CHANGE\020\013\022\014\n\010NEW_USER\020\014" +
      "\022\020\n\014SEND_MESSAGE\020\024\022\022\n\016UPDATE_MESSAGE\020\025\022\022" +
      "\n\016DELETE_MESSAGE\020\026\022\021\n\rLIST_MESSAGES\020\027\022\017\n" +
      "\013NEW_MESSAGE\020\030\022\023\n\017UPDATED_MESSAGE\020\031B\024\n\022w",
      "g_test.chat.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wg_test_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wg_test_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wg_test_ServerMessage_descriptor,
        new java.lang.String[] { "Type", "Success", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
